epochs : 50
lr : 5e-5
optimizer : Adam
lr_scheduler : {
            "type": "MultiStepLR",
            "kwargs": {
                "gamma": 0.8
            }
        }
metrics : 
loss : 
write_path : 
checkpoints_path : 
val_per_step : 
task_mode : DEN