python adl_tests.py -dataset faciesmark -cnt mixed -cnl 0.01 -tnt gaussian -tnl 0.001
python adl_tests.py -dataset faciesmark -cnt mixed -cnl 0.01 -tnt gaussian -tnl 0.01
python adl_tests.py -dataset faciesmark -cnt mixed -cnl 0.01 -tnt gaussian -tnl 0.025
python adl_tests.py -dataset faciesmark -cnt mixed -cnl 0.01 -tnt gaussian -tnl 0.05
python adl_tests.py -dataset faciesmark -cnt mixed -cnl 0.01 -tnt gaussian -tnl 0.1
python adl_tests.py -dataset faciesmark -cnt mixed -cnl 0.01 -tnt gaussian -tnl 0.25
python adl_tests.py -dataset faciesmark -cnt mixed -cnl 0.01 -tnt gaussian -tnl 0.5
python adl_tests.py -dataset faciesmark -cnt mixed -cnl 0.01 -tnt mixed -tnl 0.1
python adl_tests.py -dataset faciesmark -cnt mixed -cnl 0.01 -tnt poisson -tnl 0.1
python adl_tests.py -dataset stdata12 -cnt gaussian -cnl 0.01 -tnt gaussian -tnl 0.001
python adl_tests.py -dataset stdata12 -cnt gaussian -cnl 0.01 -tnt gaussian -tnl 0.01
python adl_tests.py -dataset stdata12 -cnt gaussian -cnl 0.01 -tnt gaussian -tnl 0.025
python adl_tests.py -dataset stdata12 -cnt gaussian -cnl 0.01 -tnt gaussian -tnl 0.05
python adl_tests.py -dataset stdata12 -cnt gaussian -cnl 0.01 -tnt gaussian -tnl 0.1
python adl_tests.py -dataset stdata12 -cnt gaussian -cnl 0.01 -tnt gaussian -tnl 0.25
python adl_tests.py -dataset stdata12 -cnt gaussian -cnl 0.01 -tnt gaussian -tnl 0.5
python adl_tests.py -dataset stdata12 -cnt gaussian -cnl 0.01 -tnt mixed -tnl 0.1
python adl_tests.py -dataset stdata12 -cnt gaussian -cnl 0.01 -tnt poisson -tnl 0.1
python adl_tests.py -dataset stdata12 -cnt gaussian -cnl 0.05 -tnt gaussian -tnl 0.001
python adl_tests.py -dataset stdata12 -cnt gaussian -cnl 0.05 -tnt gaussian -tnl 0.01
python adl_tests.py -dataset stdata12 -cnt gaussian -cnl 0.05 -tnt gaussian -tnl 0.025
python adl_tests.py -dataset stdata12 -cnt gaussian -cnl 0.05 -tnt gaussian -tnl 0.05
python adl_tests.py -dataset stdata12 -cnt gaussian -cnl 0.05 -tnt gaussian -tnl 0.1
python adl_tests.py -dataset stdata12 -cnt gaussian -cnl 0.05 -tnt gaussian -tnl 0.25
python adl_tests.py -dataset stdata12 -cnt gaussian -cnl 0.05 -tnt gaussian -tnl 0.5
python adl_tests.py -dataset stdata12 -cnt gaussian -cnl 0.05 -tnt mixed -tnl 0.1
python adl_tests.py -dataset stdata12 -cnt gaussian -cnl 0.05 -tnt poisson -tnl 0.1
python adl_tests.py -dataset stdata12 -cnt gaussian -cnl 0.1 -tnt gaussian -tnl 0.001
python adl_tests.py -dataset stdata12 -cnt gaussian -cnl 0.1 -tnt gaussian -tnl 0.01
python adl_tests.py -dataset stdata12 -cnt gaussian -cnl 0.1 -tnt gaussian -tnl 0.025
python adl_tests.py -dataset stdata12 -cnt gaussian -cnl 0.1 -tnt gaussian -tnl 0.05
python adl_tests.py -dataset stdata12 -cnt gaussian -cnl 0.1 -tnt gaussian -tnl 0.1
python adl_tests.py -dataset stdata12 -cnt gaussian -cnl 0.1 -tnt gaussian -tnl 0.25
python adl_tests.py -dataset stdata12 -cnt gaussian -cnl 0.1 -tnt gaussian -tnl 0.5
python adl_tests.py -dataset stdata12 -cnt gaussian -cnl 0.1 -tnt mixed -tnl 0.1
python adl_tests.py -dataset stdata12 -cnt gaussian -cnl 0.1 -tnt poisson -tnl 0.1
python adl_tests.py -dataset stdata12 -cnt gaussian -cnl 0.5 -tnt gaussian -tnl 0.001
python adl_tests.py -dataset stdata12 -cnt gaussian -cnl 0.5 -tnt gaussian -tnl 0.01
python adl_tests.py -dataset stdata12 -cnt gaussian -cnl 0.5 -tnt gaussian -tnl 0.025
python adl_tests.py -dataset stdata12 -cnt gaussian -cnl 0.5 -tnt gaussian -tnl 0.05
python adl_tests.py -dataset stdata12 -cnt gaussian -cnl 0.5 -tnt gaussian -tnl 0.1
python adl_tests.py -dataset stdata12 -cnt gaussian -cnl 0.5 -tnt gaussian -tnl 0.25
python adl_tests.py -dataset stdata12 -cnt gaussian -cnl 0.5 -tnt gaussian -tnl 0.5
python adl_tests.py -dataset stdata12 -cnt gaussian -cnl 0.5 -tnt mixed -tnl 0.1
python adl_tests.py -dataset stdata12 -cnt gaussian -cnl 0.5 -tnt poisson -tnl 0.1
python adl_tests.py -dataset stdata12 -cnt mixed -cnl 0.01 -tnt gaussian -tnl 0.001
python adl_tests.py -dataset stdata12 -cnt mixed -cnl 0.01 -tnt gaussian -tnl 0.01
python adl_tests.py -dataset stdata12 -cnt mixed -cnl 0.01 -tnt gaussian -tnl 0.025
python adl_tests.py -dataset stdata12 -cnt mixed -cnl 0.01 -tnt gaussian -tnl 0.05
python adl_tests.py -dataset stdata12 -cnt mixed -cnl 0.01 -tnt gaussian -tnl 0.1
python adl_tests.py -dataset stdata12 -cnt mixed -cnl 0.01 -tnt gaussian -tnl 0.25
python adl_tests.py -dataset stdata12 -cnt mixed -cnl 0.01 -tnt gaussian -tnl 0.5
python adl_tests.py -dataset stdata12 -cnt mixed -cnl 0.01 -tnt mixed -tnl 0.1
python adl_tests.py -dataset stdata12 -cnt mixed -cnl 0.01 -tnt poisson -tnl 0.1
python adl_tests.py -dataset stdata12 -cnt poisson -cnl 0.1 -tnt poisson -tnl 0.001
python adl_tests.py -dataset stdata12 -cnt poisson -cnl 0.1 -tnt mixed -tnl 0.01
python adl_tests.py -dataset stdata12 -cnt poisson -cnl 0.1 -tnt gaussian -tnl 0.01
python adl_tests.py -dataset stdata12 -cnt poisson -cnl 0.1 -tnt gaussian -tnl 0.05
python adl_tests.py -dataset stdata12 -cnt poisson -cnl 0.1 -tnt gaussian -tnl 0.1
python adl_tests.py -dataset stdata12 -cnt poisson -cnl 0.1 -tnt gaussian -tnl 0.5
python adl_tests.py -dataset stdata12 -cnt lpf -cnl 0.1 -tnt lpf -tnl 0.001
python adl_tests.py -dataset interpretation -cnt mixed -cnl 0.01 -tnt gaussian -tnl 0.001
python adl_tests.py -dataset interpretation -cnt mixed -cnl 0.01 -tnt gaussian -tnl 0.01
python adl_tests.py -dataset interpretation -cnt mixed -cnl 0.01 -tnt gaussian -tnl 0.025
python adl_tests.py -dataset interpretation -cnt mixed -cnl 0.01 -tnt gaussian -tnl 0.05
python adl_tests.py -dataset interpretation -cnt mixed -cnl 0.01 -tnt gaussian -tnl 0.1
python adl_tests.py -dataset interpretation -cnt mixed -cnl 0.01 -tnt gaussian -tnl 0.25
python adl_tests.py -dataset interpretation -cnt mixed -cnl 0.01 -tnt gaussian -tnl 0.5
python adl_tests.py -dataset interpretation -cnt mixed -cnl 0.01 -tnt mixed -tnl 0.1
python adl_tests.py -dataset interpretation -cnt mixed -cnl 0.01 -tnt poisson -tnl 0.1